### ISSUE TITLE
Exception: FileSizeExceeded when running subset with *whole* files

### ISSUE THREAD

**Issue by cehbrecht** [roocs/rook#139]
## Description

Subset workflow raises `FileSizeExceeded` error.

## Environment

* rook version used, if any: 0.4.0
* Python version, if any:
* Operating System:

## Steps to Reproduce

Running a subset (return whole files) workflow on:
```
c3s-cmip6.ScenarioMIP.MOHC.HadGEM3-GC31-LL.ssp245.r1i1p1f3.day.tas.gn.v20190908
```

 Get an pywps exception when building the metalink document:
```
Traceback (most recent call last):
  File "/usr/local/anaconda/envs/rook/lib/python3.7/site-packages/pywps/app/Process.py", line 248, in _run_process
    self.handler(wps_request, wps_response)  # the user must update the wps_response.
  File "/usr/local/src/rook/rook/processes/wps_orchestrate.py", line 96, in _handler
    response.outputs["output"].data = ml4.xml
  File "/usr/local/anaconda/envs/rook/lib/python3.7/site-packages/pywps/inout/outputs.py", line 460, in xml
    return self._template.render(meta=self)
  File "/usr/local/anaconda/envs/rook/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/anaconda/envs/rook/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/anaconda/envs/rook/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/anaconda/envs/rook/lib/python3.7/site-packages/pywps/templates/metalink/4.0/main.xml", line 14, in top-level template code
    {% if file.size %}
  File "/usr/local/anaconda/envs/rook/lib/python3.7/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
  File "/usr/local/anaconda/envs/rook/lib/python3.7/site-packages/pywps/inout/outputs.py", line 364, in size
    return os.stat(self.file).st_size
  File "/usr/local/anaconda/envs/rook/lib/python3.7/site-packages/pywps/inout/outputs.py", line 387, in file
    return self._output.file
  File "/usr/local/anaconda/envs/rook/lib/python3.7/site-packages/pywps/inout/basic.py", line 462, in file
    raise FileSizeExceeded(error_message)
pywps.exceptions.FileSizeExceeded: 400 FileSizeExceeded: File size for input "?" exceeded. Maximum allowed: 209715200.0 megabytes

```

Exception says "megabytes" ... but should be "bytes".

## Additional Information

Code in pywps:
https://github.com/geopython/pywps/blob/bbca1e42b63cf9c31c40fa3e2a731a1528adb2b9/pywps/inout/basic.py#L462

**Comment by cehbrecht** [comment]
Need to fix the unit in the error message using bytes:
```
 File "/usr/local/anaconda/envs/rook/lib/python3.7/site-packages/pywps/inout/basic.py", line 462, in file
    raise FileSizeExceeded(error_message)
pywps.exceptions.FileSizeExceeded: 400 FileSizeExceeded: File size for input "?" exceeded. Maximum allowed: 209715200.0 megabytes
```

Also in production mode we don't see this error message ... maybe use a different exception type.

**Comment by cehbrecht** [comment]
For *whole* files we are just returning URLs pointing to the data node. But the metalink extension in pywps is smart and checks the file size of those URLs. 

Need to increase the default value in pywps config:
```
maxsingleinputsize = 3000mb
maxrequestsize = 200mb
```

**Comment by cehbrecht** [comment]
Updated default in ansible deployment:
https://github.com/bird-house/ansible-wps-playbook/pull/135

Can be overwritten in `custom.yml`.
