### ISSUE TITLE
subset process fails on compute nodes

### ISSUE THREAD

**Issue by cehbrecht** [roocs/rook#64]
## Description

The subset process started to fail today at 12:00 as indicated by the GHC:
https://geohealthcheck.cloud.dkrz.de/resources?lang=en&tag=subset

The rook log has the following error message:
```
2020-10-08 21:55:58,995 - /usr/local/anaconda/envs/rook/lib/python3.7/site-packages/daops/utils/consolidate.py - INFO - Kept 5 files
2020-10-08 21:55:58,996 - /usr/local/anaconda/envs/rook/lib/python3.7/site-packages/daops/utils/normalise.py - INFO - Working on datasets: OrderedDict([('c3s-cmip5.output1.ICHEC.EC-EARTH.historical.day.atmos.day.r1i1p1.tas.latest', ['/opt/birdhouse/data/mini-esgf-data/test_data/group_workspaces/jasmin2/cp4cds1/vol1/data/c3s-cmip5/output1/ICHEC/EC-EARTH/historical/day/atmos/day/r1i1p1/tas/latest/tas_day_EC-EARTH_historical_r1i1p1_18600101-18691231.nc', '/opt/birdhouse/data/mini-esgf-data/test_data/group_workspaces/jasmin2/cp4cds1/vol1/data/c3s-cmip5/output1/ICHEC/EC-EARTH/historical/day/atmos/day/r1i1p1/tas/latest/tas_day_EC-EARTH_historical_r1i1p1_18700101-18791231.nc', '/opt/birdhouse/data/mini-esgf-data/test_data/group_workspaces/jasmin2/cp4cds1/vol1/data/c3s-cmip5/output1/ICHEC/EC-EARTH/historical/day/atmos/day/r1i1p1/tas/latest/tas_day_EC-EARTH_historical_r1i1p1_18800101-18891231.nc', '/opt/birdhouse/data/mini-esgf-data/test_data/group_workspaces/jasmin2/cp4cds1/vol1/data/c3s-cmip5/output1/ICHEC/EC-EARTH/historical/day/atmos/day/r1i1p1/tas/latest/tas_day_EC-EARTH_historical_r1i1p1_18900101-18991231.nc', '/opt/birdhouse/data/mini-esgf-data/test_data/group_workspaces/jasmin2/cp4cds1/vol1/data/c3s-cmip5/output1/ICHEC/EC-EARTH/historical/day/atmos/day/r1i1p1/tas/latest/tas_day_EC-EARTH_historical_r1i1p1_19000101-19091231.nc'])])
2020-10-08 21:55:59,197 - elasticsearch - WARNING - GET https://elasticsearch.ceda.ac.uk:443/roocs-fix/_doc/33bb2bfcf623f214c61935e225e30170 [status:400 request:0.200s]
Traceback (most recent call last):
  File "/usr/local/src/rook/rook/processes/wps_subset.py", line 91, in _handler
    result = subset(**kwargs)
  File "/usr/local/anaconda/envs/rook/lib/python3.7/site-packages/daops/ops/subset.py", line 52, in subset
    norm_collection = normalise.normalise(collection)
  File "/usr/local/anaconda/envs/rook/lib/python3.7/site-packages/daops/utils/normalise.py", line 17, in normalise
    ds = open_dataset(dset, file_paths)
  File "/usr/local/anaconda/envs/rook/lib/python3.7/site-packages/daops/utils/core.py", line 50, in open_dataset
    fix = fixer.Fixer(ds_id)
  File "/usr/local/anaconda/envs/rook/lib/python3.7/site-packages/daops/utils/fixer.py", line 24, in __init__
    self._lookup_fix()
  File "/usr/local/anaconda/envs/rook/lib/python3.7/site-packages/daops/utils/fixer.py", line 53, in _lookup_fix
    content = self.es.get(index="roocs-fix", id=id)
  File "/usr/local/anaconda/envs/rook/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 152, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/usr/local/anaconda/envs/rook/lib/python3.7/site-packages/elasticsearch/client/__init__.py", line 996, in get
    "GET", _make_path(index, doc_type, id), params=params, headers=headers
  File "/usr/local/anaconda/envs/rook/lib/python3.7/site-packages/elasticsearch/transport.py", line 392, in perform_request
    raise e
  File "/usr/local/anaconda/envs/rook/lib/python3.7/site-packages/elasticsearch/transport.py", line 365, in perform_request
    timeout=timeout,
  File "/usr/local/anaconda/envs/rook/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 269, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/anaconda/envs/rook/lib/python3.7/site-packages/elasticsearch/connection/base.py", line 301, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.RequestError: RequestError(400, 'illegal_argument_exception', "alias [roocs-fix] has more than one index associated with it [roocs-fix-2020-10-08, roocs-fix-2020-07-08], can't execute a single index op")
```

The daops call to elasticsearch returns an error:
https://elasticsearch.ceda.ac.uk/roocs-fix/_doc/33bb2bfcf623f214c61935e225e30170

## Environment

* rook version used, if any:
* Python version, if any:
* Operating System:

**Comment by cehbrecht** [comment]
@agstephens @ellesmith88 should we handle these errors with an error message? Should we proceed subsetting without applying fixes? Should fixes be applied optionally?

**Comment by agstephens** [comment]
@ellesmith88 please can you take a look at this issue - maybe it is something we need to fix in our elasticsearch interface.

**Comment by ellesmith88** [comment]
@agstephens @cehbrecht If there are 2 elastic search indices pointing to the same alias then there is an error raised. I put the esmval fixes I had generated on elasticsearch and so this must have caused the error. I'll fix this 👍

**Comment by ellesmith88** [comment]
Although I thought the point of having dated indices was that the alias would point to the most recent one. As this is not the case we will have to decide how to handle this.

**Comment by cehbrecht** [comment]
@ellesmith88 
Service is up again:
https://geohealthcheck.cloud.dkrz.de/resource/11?lang=en

Thanks :)

**Comment by ellesmith88** [comment]
Great. I think I've come up with a solution to solve the multiple indices for one alias issue as well. I just need to test it.

**Comment by agstephens** [comment]
Great @ellesmith88, maybe the query is not pointing exactly to the alias. In MOLES we have a similar issue with:

index_20200101
index_20200102
index_20200103 <-- index

The "index" is the alias and that just points to one of the actual indexes. All queries directly talk to "alias". 

However, looking at your code, and the docs (https://elasticsearch-py.readthedocs.io/en/master/api.html#elasticsearch.Elasticsearch.get), it looks like we are doing the right thing and maybe the ES library is doing something strange. I would talk to Richard about this as he may have useful insight.

**Comment by ellesmith88** [comment]
@agstephens  I just looked at MOLES - looks like when creating a new index the alias needs to be updated:

```
es.indices.update_aliases(body={
            "actions": [
                {"remove": {"alias": alias, "index": "*"}},
                {"add":    {"alias": alias, "index": index}}
            ]
        })

```
So the old index is removed from the alias and the new one added. I didn't do this when I made a new index so the alias was pointing to both. I'll implement this into the script I use the create an index.

**Comment by agstephens** [comment]
Nice spot @ellesmith88. Great stuff.

**Comment by agstephens** [comment]
Done.
